server:
  port: 8762
spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:properties
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/